<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#BarraNav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
   
      </button>
      <a class="navbar-brand" href="#">Sistema de Matriculacón</a>
    </div>
  <div class="collapse navbar-collapse" id="BarraNav">  
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Matriculados
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Cargar</a></li>
          <li><a href="#">Modificar</a></li>
        </ul>
      </li>
      <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Constacias
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="#">Constancia de matricula activa</a></li>
              <li><a href="#">Certificado de libre sancion Profesional</a></li>
          </ul>
      </li> 
    </ul>
  </div>  
  </div>
</nav>

