<?php Load::lib('QRGenerator');?>

<div class="row">
    <div class="col-md-4">
        
    </div>
    <div class="col-md-4">
        <h3>Buscar Personas</h3>
    </div>
</div>
<?php echo Form::open("constancia/buscar",'POST','class="form.horizontal"') ?>
<div class="form-group">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <label> </label>
        <?php echo Form::text('buscar1','class="form-control" placeholder="Ingrese el DNI" maxlength="8" onkeypress="return valideKey(event)" required')?>
    </div>
    <div class="col-md-4">
        <label> </label>
       <?php echo Form::submit('Buscar','class="btn btn-info pull-left" style=" position:relative; top: 18px"')?> 
    </div> 
</div>
<br>
<br>
<br>

<?php Form::close()?>
<br>
<br>
<div>
    <label> Nombre:   <?php echo $nomb?></label> <br>
    <label> Apellido: <?php echo $apell ?></label> <br>
    <label> Dni:      <?php echo $docum ?></label>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tr class="active">
            <th>Nivel de formación</th>
            <th>Profesión</th>
            <th>Título</th>
            <th>Institución Formadora</th>
            <th>Seleccione</th>
        </tr>
        <?php foreach ($listaforma as $form): ?>
        <tr class="warning">
            <?php
            echo "<td>".Load::model('formacion')->NivelFormacion($form->TipoFormacion)."</td>";
            echo "<td>".Load::model('formacion')->NombReferencia($form->Profesion)."</td>";
            //echo "<td>".$form->Profesion."</td>";
            echo "<td>".$form->Titulo."</td>";
            echo "<td>".  Load::model('formacion')->Institucion($form->instform)."</td>";
            echo "<td>".Html::linkAction("GenerarConstancia/$form->id",'Seleccionar','target="blank"')."</td>";
            ?>
        </tr>
        <?php endforeach;?>
    </table>
</div>
<?php View::content()?>

