<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Matriculacion</title>

        <?php echo Tag::css('matriculacion/bootstrap') ?>
        <?php echo Tag::css('matriculacion/general') ?>
        <?php echo Tag::js('jquery/jquery.min')?>
        <?php echo Tag::js("matriculacion/validaciones")?>
        <?php echo Tag::js('matriculacion/bootstrap.min')?>
        <?php echo Tag::js('webcam/webcam')?>

        <?php// echo Html::headLink('/turnos/img/turnos/Icono.ico', "rel='shortcut icon',type='image/x-icon'") ?>
        <!--<link rel="shortcut icon" type="image/x-icon" href="/turnos/img/turnos/Icono.ico" /> -->
        <!--<link rel="stylesheet" href="css/matriculacion/bootstrap.min.css">-->
       <!-- <script src="javascript/jquery/jquery.min.js"></script>-->
        <!--<script src="javascript/matriculacion/bootstrap.min.js"></script>-->


        <script type="text/javascript">
			$(document).ready(function(){
				$("#provi").change(function(){
					$.ajax({
						url:"<?php echo PUBLIC_PATH.'persona/procesa'?>",
						type: "POST",
						data:"NombProv="+$("#provi").val(),
						success: function(opciones){
							$("#persona_CuidadNac").html(opciones);
						}
					})
				});
			});
		</script>
        <?php echo Html::includeCss() ?>
    </head>
    <body>
        <header>
            <?php// View::partial('') ?>
        </header> 
         <?php View::partial('matriculacion/navbar');?>
        
        <div  id='bod'>                 
            <?php View::content() ?>
        </div>
       
        <footer>
            <?php// View::partial('') ?>
        </footer>
        
    </body>
</html>