<?php echo Form::open('', 'Post', 'class="form-horizontal"');?>
<div class="bodform">
    <div class="form-group">
        <div class="col-md-4">
            <label>Nombre</label>
            <?php echo Form::text('persona.Nombre','class="form-control"')?>
        </div>
        <div class="col-md-4">
            <label>Apellido</label>
            <?php echo Form::text('persona.Apellido', 'class="form-control"')?>
        </div>
        <div class="col-md-4">
            <label>Fecha de nacimiento</label>
            <?php echo Form::date('persona.FechaNac','class="form-control"')?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <?php $tipo = array(0=>'DNI',1=>'L.E.',2=>'L.C.');?>
            <label>Tipo de documento</label>
            <?php echo Form::select('documento.tipodoc',$tipo,'class="form-control"');?>
        </div>
        <div class="col-md-4">
            <label>Nro de DNI</label>
            <?php echo Form::text('documento.nrodoc','class="form-control"')?>
        </div>
    </div>
</div>

<?php echo Form::close()?>

