<!------------------------------------- FORMACION----------------------------------->
  <div class="panel-group" id="accordion">
      <div class="panel panel-default"> 
          <div class="panel-heading">
              <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                  DATOS PERSONALES
              </h4>
          </div>  
          <div id="collapse1" class="panel-collapse collapse">
            <div class="panel-body"> 
            
            <?php echo Form::openMultipart('persona/create','class="form-horizontal" id="form1" onsubmit=""') ?> 
            <div class="bodform">    
           <fieldset disabled="true">    
            <div class="form-group">
                <div class="col-md-4">
                    <label>Nombre</label>
                    <?php echo Form::text('persona.Nombre','class="form-control" placeholder="Ingrese el Nombre" onkeypress="return valideKey2(event)" style="text-transform:uppercase"')?>
                </div>
                <div class="col-md-4">
                    <label>Apellido</label>
                    <?php echo Form::text('persona.Apellido', 'class="form-control" placeholder="Ingrese el Apellido" onkeypress="return valideKey2(event)" style="text-transform:uppercase"')?>
                </div>
                <div class="col-md-4">
                    <label>Fecha de nacimiento</label>
                    <?php echo Form::date('persona.FechaNac','class="form-control"')?>
                </div>
            </div>
                
                
            <div class="form-group">
                <div class="col-md-2">
                    <?php $tipo = array(1=>'DNI',3=>'L.E.',2=>'L.C.',4=>'CI',5=>'DE',6=>'DNIF',7=>'DNIM');?>
                    <label>Tipo de documento</label>
                    <?php echo Form::select('documento.tipodoc',$tipo,'class="form-control"');?>
                </div>
                <div class="col-md-4">
                    <label>Nro de DNI</label>
                    <?php echo Form::text('persona.dni','class="form-control" placeholder="Ingrese el Nro de Documento" maxlength="8" onkeypress="return valideKey(event)"')?>
                </div>
                 <div class="col-md-2">
                    <label>Sexo</label>
                    <div class="radio">
                        <label><?php echo Form::radio('persona.Sexo', 'M','onchange="return CuilH(persona_dni,persona_CuilCuit)"')?>Masculino </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <label> </label>
                    <div class="radio">
                        <label><?php echo Form::radio('persona.Sexo', 'F','onchange="return CuilM(persona_dni,persona_CuilCuit)"')?> Femenino</label>
                    </div>
                </div>

            </div>
                
                
            <div class="form-group">
                <div class="col-md-4">
                    <label>Cuil</label>
                    <?php echo Form::text('persona.CuilCuit','class="form-control" placeholder="Ingrese DNI y seleccione el Sexo" readonly');?>
                </div>
                 <div class="col-md-4">
                    <label>Pais de Nacimiento</label>
                    <?php echo Form::dbSelect('persona.PaisNac', 'Pais', array('pais_nacionalidad','paisord'), '--Seleccionar Pais de Nacimiento--', 'class="form-control"')?>
                </div>
                <div class="col-md-4">
                    <label>Nacionalidad</label>
                        <?php echo Form::dbSelect('persona.Nacionalidad', 'Nacionalidad', array('pais_nacionalidad','nacord'), '--Seleccionar Nacionalidad--', 'class="form-control"')?>
                </div>
            </div>
                
                
            <div class="form-group">
                 <div class="col-md-4">
                    <label>Ciudad de nacimiento</label>
                    <?php// echo Form::text('persona.CiudadNac','class="form-control" placeholder="Ciudad de nacimiento"')?>
                    <?php echo Form::dbSelect('persona.CuidadNac','Localidad',array('ciudad_nacimiento','ciudadord'),'--Seleccionar Ciudad de Nacimiento--','class="form-control"')?>
                </div>
                <div class="col-md-4">
                    <label>Domicilio (calle)</label>
                    <?php echo Form::text('persona.DomCalle','class="form-control" placeholder="Nombre de la calle" style="text-transform:uppercase"');?>
                </div>
                <div class="col-md-1">
                    <label>Nro</label>
                    <?php echo Form::text('persona.DomNro','class="form-control" placeholder="Numero" onkeypress="return valideKey(event)"')?>
                </div>
                <div class="col-md-1">
                    <label>Piso</label>
                    <?php echo Form::text('persona.DomPiso','class="form-control" placeholder="Piso" onkeypress="return valideKey(event)"')?>
                </div>
                <div class="col-md-2">
                    <label>Dpto</label>
                    <?php echo Form::text('persona.DomDepto','class="form-control" placeholder="Departamento"');?>
                </div>  
            </div>
                
                
            <div class="form-group">
                <div class="col-md-4">
                    <label>Barrio</label>
                    <?php echo Form::text('persona.Barrio','class="form-control" placeholder="Ingrese el Barrio" style="text-transform:uppercase"');?>
                </div>
                <div class ="col-md-4">
                    <label>Mail</label>
                    <?php echo Form::text('persona.Mail','class="form-control" placeholder="E-mail" onblur="return validarEmail2(this.value,helpBlock)" style="text-transform:lowercase"');?>
                    <span id="errmail"></span>
                    <span id="helpBlock" class="help-block"></span>
                </div>
                <div class="col-md-4">
                        <label> </label> 
                        <div class="check">
                            <label>Tiene Telefono <?php echo Form::check('telefono.TieneTel','1','onchange="return HabilitarTel1(this.id,agregar1,agregar2,agregar3,tel1,tel2,tel3,tel4)"',false )?> </label> 
                        </div>                  
                </div>
            </div>
             
            <div class="form-group">
                <?php $tipotel = array('CELULAR'=>'CELULAR','TELEFONO/FAX'=>'TELEFONO/FAX','PARTICULAR'=>'PARTICULAR','PARTICULAR/VECINO'=>'PARTICULAR/VECINO','LABORAL'=>'LABORAL','OTROS/DESCONOCIDO'=>'OTROS/DESCONOCIDO')?>
                <div id="tel1">
                <div id="" class="col-md-2">
                    <label>Seleccione tipo </label>
                    <?php echo Form::select('telefono.Tipo1', $tipotel, 'class="form-control"')?>
                </div>  
                <div id="" class="col-md-2">
                    <label> Telefono 1</label>
                    <?php echo Form::text('telefono.NumTel1','class="form-control placeholder="Ingrese Telefono"')?>
                </div>
                <div id="" class="col-md-2">
                    <label> </label>
                    <div class="check">
                        <label><?php echo Form::check('agregar1','','onchange="return HabilitarTel2(this.id,agregar2,agregar3,tel2,tel3,tel4)"',false)?> Agregar otro telefono</label>
                    </div>
                </div>
                </div>
                
                <div id="tel2">
                <div class="col-md-2">
                    <label>Seleccione tipo </label>
                    <?php echo Form::select('telefono.Tipo2', $tipotel, 'class="form-control"')?>
                </div>  
                <div class="col-md-2">
                    <label> Telefono 2</label>
                    <?php echo Form::text('telefono.NumTel2','class="form-control placeholder="Ingrese Telefono"')?>
                </div>
                <div class="col-md-2">
                    <label> </label>
                    <div class="check">
                        <label><?php echo Form::check('agregar2','','onchange="return HabilitarTel3(this.id,agregar3,tel3,tel4)"',false)?> Agregar otro telefono</label>
                    </div>
                </div>
                </div>
            </div>   
                
             <div class="form-group">
                <div id="tel3">
                    <div class="col-md-2">
                        <label>Seleccione tipo </label>
                        <?php echo Form::select('telefono.Tipo3', $tipotel, 'class="form-control"')?>
                    </div>  
                    <div class="col-md-2">
                        <label> Telefono 3</label>
                        <?php echo Form::text('telefono.NumTel3','class="form-control placeholder="Ingrese Telefono"')?>
                    </div>
                    <div class="col-md-2">
                        <label> </label>
                        <div class="check">
                            <label><?php echo Form::check('agregar3','','onchange="return HabilitarTel4(this.id,tel4)"',false)?> Agregar otro telefono</label>
                        </div>
                    </div>
                </div>
                
                <div id="tel4">
                    <div class="col-md-2">
                        <label>Seleccione tipo </label>
                        <?php echo Form::select('telefono.Tipo4', $tipotel, 'class="form-control"')?>
                    </div>  
                    <div class="col-md-2">
                        <label> Telefono 4</label>
                        <?php echo Form::text('telefono.NumTel4','class="form-control placeholder="Ingrese Telefono"')?>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>
            </div>                 
 
            <div class="form-group">
              <div class="col-md-12">
                  <?php echo Form::submit('Guardar','id="btnpersona" class= "btn btn-info pull-right" disabled="True" onclick=""')?>
                  <?php// return HabilitarBtn(this.id,btnformacion,form1)?>
              </div>
            </div>
   
           </fieldset>
            </div>  
            
            <?php echo Form::close()?>    
          </div>  
      </div>
  </div>

   <!------------------------------------------------------------------------------------------
   --------------------------------------------------------------------------------------------
   --------------------------------  Datos Profecionales---------------------------------------
   --------------------------------------------------------------------------------------------
   -------------------------------------------------------------------------------------------->  
   
   
  <div class="panel panel-default"> 
      <div class="panel-heading">
          <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion" href="#collapse2">
              DATOS PROFESIONALES
          </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse in">
          <div class="panel-body">
             <?php echo Form::openMultipart("persona/AltaFormacion/$param1", 'class="form-horizontal"') ?> 
              <div class="bodform">
                  <div class="form-group">
                      <div class="col-md-4">
                          <?php $formaciones = array(0=>'--Seleccionar tipo de Profesión',3=>'UNIVERSITARIO',2=>'TECNICO',1=>'AUXILIAR')?>
                          <label>Tipo de formacion</label>
                          <?php echo Form::select('formacion.TipoFormacion', $formaciones,'class="form-control" onclick="return HabilitarBtn(btnpersona,btnformacion)"','--Seleccionar tipo de Formación required')?>
                      </div>
                      <div class="col-md-4">
                          <label>Profesión</label>
                          <?php echo Form::dbSelect('formacion.Profesion','profesion',array('profesiones','ProfesOrde2'),'--Seleccionar Pofesion--','class="form-control" required');?>
                      </div>
                      <div class="col-md-4">
                          <label>Título</label>
                          <?php echo Form::text('formacion.Titulo', 'class="form-control" placeholder="Ingrese el Título" required')?>
                      </div>
                  </div>
                  
                  <div class="form-group">
                      <div class="col-md-4">
                          <label>Fecha de Titulo</label>
                          <?php echo Form::date('formacion.FechaTitulo','class="form-control" required')?>
                      </div>
                      <div class="col-md-4">
                          <label>Fecha de Egreso</label>
                          <?php echo Form::date('formacion.FechaEgreso','class="form-control" required')?>
                      </div>
<!--                      <div class="col-md-4">
                          <label>Profesión de Referencia</label>
                          <?php //echo Form::dbSelect('formacion.ProfesionReferencia', 'prf_refe', array('profesion','proforde'), '--Seleccionar Profesion de Referencia--','class="form-control" required')?>
                      </div>-->
                      <div class="col-md-4">
                          <label>Institución Formadora</label>
                          <?php echo Form::dbSelect('formacion.instform','nombre',array('inst_form','instorde'),'--Seleccione Institucion Formadora--','class="form-control" required')?>
                      </div>
                  </div>
                  
                   <div class="form-group">
                       <div class="col-md-4">
                          <label>Profesional Asociado</label>
                          <?php echo Form::text('formacion.ProfesionalAsociado','class="form-control" placeholder="Ingrese Profecional Asociado"')?>
                      </div>
                       <div class="col-md-4">
                           <label>Organismo de registro</label>
                           <?php echo Form::text('formacion.OrganismoRegistro','class="form-control" placeholder="Ingrese Organismo de Registro"')?>
                       </div>
                      <div class="col-md-2">
                          <label>Revalida</label>
                          <div class="radio">
                              <label><?php echo Form::radio('formacion.Revalida', 'SI', 'onclick="return SiReval(FecRev,InstRev)"', FALSE)?> SI</label>
                          </div>
                      </div>
                      <div class="col-md-2">
                          <label> </label>
                          <div class="radio">
                              <label><?php echo Form::radio('formacion.Revalida', 'NO', 'onclick="return NoReval(FecRev,InstRev)"', True)?> NO</label>
                          </div>
                      </div>
                  </div> 
                  
                   <div class="form-group">
                      <div id="FecRev" class='col-md-4'>
                          <label>Fecha de Reválida</label>
                          <?php echo Form::date('formacion.FechaRevalida', 'class="form-control"')?>
                      </div>
                       <div id="InstRev" class="col-md-4">
                           <label>Inst. Revalización</label>
                           <?php echo Form::dbSelect('formacion.InstitucionRevalida','nombre',array('inst_form','instorde'),'--Seleccione Institucion Formadora--','class="form-control"')?>
                       </div>
                  </div>
                  
                  <div class="form-group">
                      <div class="col-md-12">
                          <button id="btnformacion" type="submit" class="btn btn-info pull-right" onclick="return Mayus2()">Guardar</button>
                      </div>
                  </div>          
              </div>
             <?php echo Form::close()?> 
          </div>
      </div>
  </div>  
   <!------------------------------------------------------------------------------------------
   --------------------------------------------------------------------------------------------
   --------------------------------  Datos de Matricula----------------------------------------
   --------------------------------------------------------------------------------------------
   -------------------------------------------------------------------------------------------->
   
   <div class="panel panel-default"> 
      <div class="panel-heading">
          <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion" href="#collapse3">
              DATOS DE MATRICULA
          </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
          <div class="panel-body">
              <?php echo Form::openMultipart('persona/matricula1', 'class="form-horizontal"')?>
                <div class="bodform">
                    
                    <div class="form-group">
                        <div class="col-md-4">
                            <label>Fecha de matrícula</label>
                            <?php echo Form::date('matriculacion.FechaMat','class="form-control"')?>                              
                        </div>
                        <div class="col-md-4">
                            <label>Provincia</label>
                            <?php echo Form::dbSelect('matriculacion.Provincia','nombre',array('provincia','ProvOrd'),'--Seleccionar Provincia--','class="form-control"')?>
                        </div>
                        <div class="col-md-4">
                            <label>Profesión Matriculada</label>
                            <?php echo Form::dbSelect('matriculacion.Profesionmat','profesion',array('profesiones','ProfesOrde'),'--Seleccionar Profesion Matriculada--','class="form-control" maxlength="10"')?>
                        </div>
                    </div> 
                    
                    <div class="form-group">

                        <div class="col-md-2">
                            <label>Publicado en SIISA</label>
                            <div class="radio">
                                <label><?php echo Form::radio('matriculacion.Situacion',1,'',FALSE)?> SI</label>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label> </label>
                            <div class="radio">
                                <label><?php echo Form::radio('matriculacion.Situacion',0,'',TRUE)?> NO</label>
                            </div>
                        </div>

                    </div>
                    
                  <div class="form-group">
                      <div class="col-md-12">
                          <button id="btnmatriculacion" type="submit" class="btn btn-info pull-right" disabled="True">Guardar</button>
                      </div>
                  </div>   
                    
                </div>
              <?php echo Form::close()?>

              
          </div>
      </div>
  </div>        
</div>