<?php Tag::js('webcam/webcam') ?>
<script language="JavaScript">
		Webcam.set({
			width: 320,
			height: 240,
			image_format: 'jpeg',
			jpeg_quality: 90,
                        swfURL: 'matriculacion/default/public/javascript/webcam/webcam.swf'
		});
		Webcam.attach( '#my_camera' );
</script>

<form>
        <div>
          <script>
            document.write(webcam.get_html(320, 240));
          </script>
        </div>
      <input type=button value="Take Snapshot" onClick="take_snapshot()">
</form>

<script language="JavaScript">
		function take_snapshot() {
			// take snapshot and get image data
			Webcam.snap( function(data_uri) {
				// display results in page
				document.getElementById('results').innerHTML = 
					'<h2>Here is your image:</h2>' + 
					'<img src="'+data_uri+'"/>';
			} );
		}
</script>