<div class="row">
    <div class="col-md-4">
        
    </div>
    <div class="col-md-4">
        <h3>Buscar Personas</h3>
    </div>
</div>
<?php echo Form::open("",'POST','class="form.horizontal"') ?>
<div class="form-group">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <label> </label>
        <?php echo Form::text('verificar1','class="form-control" placeholder="Ingrese el DNI" maxlength="8" onkeypress="return valideKey(event)" required')?>
    </div>
    <div class="col-md-4">
        <label> </label>
       <?php echo Form::submit('Buscar','class="btn btn-info pull-left" style=" position:relative; top: 18px"')?> 
    </div> 
</div>
<br>
<br>
<br>

<?php Form::close()?>

